### ISSUE TITLE
Urusei Yatsura + Movies/OAVs [JPSDR]

### ISSUE THREAD

**Issue by seedtheworld** [thegreatestminer/acp#1]
Hiya.
Another request!
Urusei Yatsura BDrip 1080p   

https://nyaa.si/view/1242601  https://nyaa.si/view/1245145   

Those are the complete versions with acceptable quality!   

Thank you!

**Comment by thegreatestminer** [comment]
@seedtheworld Thanks for reminding me about this series. I was originally planning on getting Kagura's release on BakaBT, but JPSDR's release contains the movies as well.

I will add this to the list! Thank you for being the first person to request something here. ^-^

**Comment by seedtheworld** [comment]
Oh not at all. I'm the one who's grateful to get to have and download from this superb collection. 

PS. Regarding Urusei Yatsura, why not add Kagura's as well? Since this release this grainless whilst Kagura's is as grainy as they come!

**Comment by thegreatestminer** [comment]
@seedtheworld Sure! Luckily it's freeleech so I should be able to get it over the week.

**Comment by seedtheworld** [comment]
@thegreatestminer awesome. Thanks mate.

**Comment by thegreatestminer** [comment]
Alrighty, JPSDR's release has been completed. I am currently downloading Kagura's release as well.

Since this request was originally for JPSDR's release, I'll be closing this issue. Please check [here](https://trello.com/b/dPsfc71e/anime-collection-initiative) for progress updates.
