### ISSUE TITLE
Yu Yu Hakusho BD 1080p

### ISSUE THREAD

**Issue by seedtheworld** [thegreatestminer/acp#10]
Hi. I'm here with another classical request. 

~https://nyaa.si/view/246449~    https://nyaa.si/view/375603

https://nyaa.si/view/1097262

https://nyaa.si/view/1130902

https://nyaa.si/view/798931

Thanks in advance.

**Comment by thegreatestminer** [comment]
Hmm, to start things off, the first and last torrents are dead. Fortunately, the OVA and the movie is still well seeded, so I'm going to work on that first.

To replace the main series, I will be downloading [[Yellow-Flash] Yu Yu Hakusho (v2, 10bit, 960x720, FLAC)](https://nyaa.si/view/1252024) instead.

In addition, I will also get the second movie, [Yu Yu Hakusho - Poltergeist Report (High Quality)(Dual Audio) MKV [1080p] Blu-Ray Rip](https://nyaa.si/view/1113657).

**Comment by seedtheworld** [comment]
I am so so sorry. I gave you the wrong link for the main series.
Here's the correct link

https://nyaa.si/view/375603

**Comment by thegreatestminer** [comment]
@seedtheworld Alright, I'll get that as well.

**Comment by seedtheworld** [comment]
@thegreatestminer thank you

**Comment by thegreatestminer** [comment]
Done!

https://weeb.ztgasdf.workers.dev/Yu%20Yu%20Hakusho/

**Comment by seedtheworld** [comment]
Wow that fast. Again. Thanks.
