### ISSUE TITLE
Three requests

### ISSUE THREAD

**Issue by seedtheworld** [thegreatestminer/acp#11]
Hi again. 

[Anime Land] Dragon Quest - Your Story (Dual Audio) (BDRip 1080p HEVC DTS-HD EAC3) [549CE40A]
https://nyaa.si/view/1250961

[DmonHiro] Project K - Seven Stories (BD, 1080p)
https://nyaa.si/view/1253885

[BlurayDesuYo] Junketsu no Maria - Batch (BD 1920x1080 10bit FLAC)
https://nyaa.si/view/737535

**Comment by thegreatestminer** [comment]
I'm on it!

**Comment by thegreatestminer** [comment]
Done.

**Comment by seedtheworld** [comment]
> Done.

Legend.
