### ISSUE TITLE
[Quazza] Kimagure Orange Road [TV + Movie + OVAs] [BD 1080p] [Hi10p]

### ISSUE THREAD

**Issue by seedtheworld** [thegreatestminer/acp#13]
Hello. By now you should know I'm here to enrich your collection with great oldies!

https://nyaa.si/view/1168412
https://nyaa.si/view/1243388

Or Moozzi2's raw version if it's a better quality :

https://nyaa.si/view/1164976 / https://nyaa.si/view/1135002
https://nyaa.si/view/1164977

Thank you mate

**Comment by thegreatestminer** [comment]
Getting it right now.

**Comment by thegreatestminer** [comment]
Done!

https://weeb.ztgasdf.workers.dev/Kimagure%20Orange%20Road/

**Comment by seedtheworld** [comment]
Thanks!
