### ISSUE TITLE
Orange TV+Movie/ K Project 

### ISSUE THREAD

**Issue by seedtheworld** [thegreatestminer/acp#14]
Hi. Here to request two anime to be added:

1. Orange TV and Movie:

https://nyaa.si/view/988765
https://nyaa.si/view/1255062

2. K:
I know you've added S01 and the Movie but here are better versions to DL (bakabt freeleech):

https://bakabt.me/torrent/176501/k-project-k-k-project-2012-bd-1080p-animenow
https://bakabt.me/torrent/345784/k-return-of-kings-1080p-kbaraka
https://bakabt.me/torrent/347551/gekijouban-k-missing-kings-bd-1080p-vcb-anna

Thank you again.

**Comment by thegreatestminer** [comment]
I will work on it!

**Comment by seedtheworld** [comment]
> I will work on it!

Thank you!

**Comment by thegreatestminer** [comment]
Orange has been added.

https://weeb.ztgasdf.workers.dev/Orange/

**Comment by thegreatestminer** [comment]
Added the other three torrents. https://weeb.ztgasdf.workers.dev/K%20Project/
