### ISSUE TITLE
Video Girl Ai & MM!

### ISSUE THREAD

**Issue by Tonythemaster999** [thegreatestminer/acp#15]
Hello, I would like to make a request for two animes

MM! 
English sub: https://nyaa.si/view/1051011

Video Girl Ai 
English sub: https://nyaa.si/view/70423

Raw: https://nyaa.si/view/200782

(Included Raw too since I think it is slightly better than the english subbed)
(might rip the subtitles from the english one and sync it up to this torrent, idk)

**Comment by thegreatestminer** [comment]
I'll work on it! For MM!, I will get AC's release as well.

**Comment by thegreatestminer** [comment]
SNS's release for Video Girl Ai on Nyaa is poorly seeded, currently stalled at 60MB/1.8GB, but BakaBT has it available, but I don't have enough ratio to download it.

Luckily, AnimeTosho has the attachments available, so I am able to get that instead. The raws are currently downloading, so there's that still.

**Comment by thegreatestminer** [comment]
Scratch that, SNS's release was able to finish downloading.

Here you go!

http://weeb.ztgasdf.workers.dev/MM!/
https://weeb.ztgasdf.workers.dev/Video%20Girl%20Ai/
