### ISSUE TITLE
[Yousei-raws] UN-GO [BDrip 1920x1080 x264 FLAC]

### ISSUE THREAD

**Issue by thatanimeguy** [thegreatestminer/acp#16]
Hello. Can you upload this version please?
https://nyaa.si/view/308322
https://nyaa.si/view/307506
Or (the same but different tracker/site)
https://rutracker.org/forum/viewtopic.php?t=3954552
https://rutracker.org/forum/viewtopic.php?t=4070586

BDRemux
https://rutracker.org/forum/viewtopic.php?t=5224096
https://rutracker.org/forum/viewtopic.php?t=5215190

----------‐-------------------------------------------------------
https://nyaa.si/view/310746

The BDs are preferable than the REMUXs

**Comment by thegreatestminer** [comment]
This is a tricky one... I'll try to get it.

**Comment by thegreatestminer** [comment]
Quick summary:

- **[Yousei-raws] UN-GO [BDrip 1920x1080 x264 FLAC]** | Downloading, okay speeds
- **[Yousei-raws] UN-GO episode：0 Inga-ron [BDrip 1920x1080 x264 FLAC]** | Dead torrent
- **[Zurako]\_UN-GO_00_Inga-ron_(BD_720p_AAC)_[57DD59D6].mkv** | Downloading, slow speeds
- **Ан-Го / Un-Go (Мидзусима Сэйдзи) [TV] [без хардсаба] [11 из 11] [RUS(ext)+JAP+Sub] [2011, приключения, детектив, BDRip] [1080p]** | Skipped
- **Ан-Го: Пролог / Un-Go: Inga-ron [Movie] [без хардсаба] [RUS(int), JAP+Sub] [2011, приключения, BDRip] [1080p]** | Dead torrent
- **Ан-Го / Un-Go (Мидзусима Сэйдзи) [TV+Special] [без хардсаба] [11+10 из 11+10] [JAP+Sub] & [11+0 из 11+10] [RUS(ext)] [2011, приключения, детектив, BDRemux] [1080p]** | Downloaded
- **Ан-го: Пролог / Un-Go: Inga-ron (Мидзусима Сэйдзи) [Movie] [1 из 1] [без хардсаба] [RUS(ext), JAP+Sub] [2011, приключения, детектив, BDRemux] [1080p]** | Downloaded

---

Progress is being made, I apologize that the movie will only be in BDRemux.

**Comment by thatanimeguy** [comment]
What the... why are YOU apologising? I'm grateful for whatever I can get. Thanks bruh.

**Comment by thegreatestminer** [comment]
It's done...!

```
rclone size backup:Anime/UN-GO
Total objects: 281
Total size: 133.500 GBytes (143344251925 Bytes)
```

http://weeb.ztgasdf.workers.dev/UN-GO/

**Comment by seedtheworld** [comment]
muchas gracias amigos!
