### ISSUE TITLE
Soul Eater/ Soul Eater Not! BD 1080p 

### ISSUE THREAD

**Issue by thatanimeguy** [thegreatestminer/acp#17]
https://nyaa.si/view/1002639
https://nyaa.si/view/722640

Thanks again.

**Comment by thegreatestminer** [comment]
Working on it!

**Comment by thegreatestminer** [comment]
Done!

https://weeb.ztgasdf.workers.dev/Soul%20Eater/

**Comment by thatanimeguy** [comment]
Thanks!😘
