### ISSUE TITLE
Girls und Panzer der Film

### ISSUE THREAD

**Issue by xxaudreyxx** [thegreatestminer/acp#19]
Hi,
I would like to request Girls und Panzer der Film.

Torrent link:
https://nyaa.si/view/815761
or
https://nyaa.si/view/828220

Many thanks in advance!

**Comment by thegreatestminer** [comment]
Huh, I thought I had this in the collection! Working on it right now.

**Comment by thegreatestminer** [comment]
Done! I also added the other extras, like das FINALE and the film OVA.

https://weeb.ztgasdf.workers.dev/Girls%20und%20Panzer/

**Comment by xxaudreyxx** [comment]
Thank you so much!! I really really appreciate it!
