### ISSUE TITLE
Ranma 1/2 (BD 1080p) [BBT-RMX] Complete Collection

### ISSUE THREAD

**Issue by seedtheworld** [thegreatestminer/acp#2]
@thegreatestminer 

Sorry for being greedy but since this is freeleech as well and I've been wanting to watch it for a long time... here are the links!

https://bakabt.me/torrent/347174/ranma-1-2-bd-1080p-bbt-rmx
https://bakabt.me/torrent/183626/ranma-1-2-ova-bd-1080p-bbt-rmx
https://bakabt.me/torrent/344698/ranma-1-2-special-bd-1080p-bbt-rmx
https://bakabt.me/torrent/344699/ranma-1-2-super-bd-1080p-bbt-rmx
https://bakabt.me/torrent/183829/ranma-1-2-chou-musabetsu-kessen-ranma-team-vs-densetsu-no-houou-ranma-1-2-decisive-battle-team-ranma-vs-the-legendary-phoenix-bd-1080p-bbt-rmx
https://bakabt.me/torrent/183828/ranma-1-2-chuugoku-nekonron-daikessen-okite-yaburi-no-gekitou-hen-ranma-1-2-big-trouble-in-nekonron-china-bd-1080p-bbt-rmx
https://bakabt.me/torrent/183827/ranma-1-2-kessen-tougenkyou-hanayome-o-torimodose-ranma-1-2-nihao-my-concubine-bd-1080p-bbt-rmx

Thanks!

**Comment by thegreatestminer** [comment]
Whew, this is massive. I'll work on this in a bit, still downloading Kagura's release of Urusei Yatsura.

You're not greedy at all for requesting stuff! Gives me things to do. :D

**Comment by seedtheworld** [comment]
@thegreatestminer 
Thank you.😊

**Comment by thegreatestminer** [comment]
Done!

https://weeb.ztgasdf.workers.dev/Ranma%201-2/
