### ISSUE TITLE
Tenchi Muyo BD 1080p

### ISSUE THREAD

**Issue by seedtheworld** [thegreatestminer/acp#20]
Hi hi. Here with another request. 

https://nyaa.si/view/925345
https://nyaa.si/view/184945

https://nyaa.si/view/1079650
https://nyaa.si/view/1080311
https://nyaa.si/view/1042255
https://nyaa.si/view/1052405
https://nyaa.si/view/1121525

https://nyaa.si/view/1184639

Thank you!

**Comment by thegreatestminer** [comment]
I'll take a look, some of these have low seeder counts. I'll report in a bit with a summary.

**Comment by thegreatestminer** [comment]
Here's the overview:

- [Tenchi Muyo! Ryo-Ohki (1992) [Doki][1448x1052 Hi10P BD FLAC]](https://nyaa.si/download/925345.torrent) | Downloading slowly, ETA ~3 days
- [Tenchi_Muyo_Ryo_Ohki_(1992)_[1080p,BluRay,x264]_-_THORA](https://nyaa.si/download/184945.torrent) | **Dead torrent**
- [[Koten_Gars] Tenchi Muyo! Ryo-Ohki OVA 1 v2 [BD][Hi10][1080p][FLAC] (Dual Audio)](https://nyaa.si/download/1079650.torrent) | **Dead torrent**
- [[Koten_Gars] Tenchi Muyo! Ryo-Ohki OVA 2 v2 [BD][Hi10][1080p][FLAC] (Dual Audio)](https://nyaa.si/download/1080311.torrent) | **Dead torrent**
- [[Koten_Gars] Tenchi Muyo! Ryo-Ohki OVA 3v2 [BD][Hi10][1080p][AC3+FLAC] (Dual Audio)](https://nyaa.si/download/1042255.torrent) | Downloading slowly, ETA ~3 hours
- [[Koten_Gars] Tenchi Muyo! Ryo-Ohki OVA 4v2 [BD][Hi10][1080p][FLAC] (English Subbed)](https://nyaa.si/download/1052405.torrent) | Downloading okay-ish, ETA ~1 hour
- [[Koten_Gars] Tenchi Muyo! - The Movie 1-3 [JP.BD][Hi10][1080p][TrueHD] (Dual Audio)](https://nyaa.si/download/1121525.torrent) | **Dead or barely alive**
- [Tenchi Muyo! Ryo-Ohki S1-S4 (BDRip 1440x1080p x265 HEVC FLACx2 5.1+2.0)(Dual Audio)[sxales]](https://nyaa.si/download/1184639.torrent) | Downloading

As you can see, there are some that are dead. I will investigate later for other torrents and I will also check some IRC packlists as well.

**Comment by seedtheworld** [comment]
Thanks. I originally planned to request only Doki and Koten 3 and 4. So it's absolutely fine as is. Thanks again!

**Comment by thegreatestminer** [comment]
Everything's downloaded, currently uploading now.

**Comment by seedtheworld** [comment]
Nice... ta

**Comment by thegreatestminer** [comment]
Done!

http://weeb.ztgasdf.workers.dev/Tenchi%20Muyo/

**Comment by seedtheworld** [comment]
@thegreatestminer What happened to Doki release?
https://nyaa.si/view/925345#comments
It wasn't added to the folder...
