### ISSUE TITLE
missing episode

### ISSUE THREAD

**Issue by Pyfiend** [thegreatestminer/acp#21]
Hello again...I just wanted to point out that Episode 12, under sub-dir [0x539] Seishun Buta Yarou wa Bunny Girl Senpai no Yume o Minai (BD 1080p x265 10bit FLAC), under directory Seishun Buta Yarou wa Bunny Girl Senpai no Yume o Minai, is missing.  Thank you for reading!

**Comment by thegreatestminer** [comment]
Confirmed, working on it right now.

**Comment by thegreatestminer** [comment]
Fixed. Sorry for the inconvenience.

https://weeb.ztgasdf.workers.dev/Seishun%20Buta%20Yarou%20wa%20Bunny%20Girl%20Senpai%20no%20Yume%20o%20Minai/[0x539]%20Seishun%20Buta%20Yarou%20wa%20Bunny%20Girl%20Senpai%20no%20Yume%20o%20Minai%20(BD%201080p%20x265%2010bit%20FLAC)/[0x539]%20Seishun%20Buta%20Yarou%20wa%20Bunny%20Girl%20Senpai%20no%20Yume%20o%20Minai%20-%2012%20(BD%201080p%20x265%2010bit%20FLAC)%20[2A324BCD].mkv

**Comment by Pyfiend** [comment]
Not a problem.  Thank you so much!
