### ISSUE TITLE
Black Clover Bluray 1080p

### ISSUE THREAD

**Issue by seedtheworld** [thegreatestminer/acp#23]
Hi.

I did request Black Clover before but unfortunately the version that was uploaded (Judas) was a re-encoded bit-starved release which is unwatchable.

This one on the other hand has superior quality.

https://nyaa.si/user/iAHQ?f=0&c=0_0&q=Black+clover+

Please grab if can.

**Comment by thegreatestminer** [comment]
:+1:

**Comment by thegreatestminer** [comment]
Added!

https://weeb.ztgasdf.workers.dev/Black%20Clover/

**Comment by seedtheworld** [comment]
Appreciated!
