### ISSUE TITLE
The Godzilla anime movies please

### ISSUE THREAD

**Issue by Sanedrac98** [thegreatestminer/acp#24]
https://nyaa.si/?f=0&c=0_0&q=%5BLowPower-Raws%5D+Godzilla

**Comment by thegreatestminer** [comment]
Considering most of them are low seeded/dead, I'll find another source that's not LowPower.

**Comment by thegreatestminer** [comment]
Done! (thanks Lelouch@animekaizoku)

https://weeb.ztgasdf.workers.dev/0:/!%20Movies/Godzilla%20Part%201%20-%20Planet%20of%20the%20Monsters%20(2017)/
https://weeb.ztgasdf.workers.dev/0:/!%20Movies/Godzilla%20Part%202%20-%20City%20on%20the%20Edge%20of%20Battle%20(2018)/
https://weeb.ztgasdf.workers.dev/0:/!%20Movies/Godzilla%20Part%203%20-%20The%20Planet%20Eater%20(2018)/

**Comment by Sanedrac98** [comment]
Thanks!!!
