### ISSUE TITLE
Detective Conan

### ISSUE THREAD

**Issue by Shane01638** [thegreatestminer/acp#25]
Please add Detective Conan.  Also, what is the best way to download more than one file at a time.  I found a couple scripts to scrape GoIndex locations but haven't learned how to use them yet.

**Comment by thegreatestminer** [comment]
![image](https://user-images.githubusercontent.com/19188146/89738073-dcc84d80-da43-11ea-9afd-95e2d3d22176.png)

Anyways, you can copy the link locations and toss them into JDownloader or a text file and let aria2 process it.
