### ISSUE TITLE
[Golo] Shigofumi [BD][1280x720] 

### ISSUE THREAD

**Issue by DankMemzYT** [thegreatestminer/acp#26]
Hey can you please add this:
https://nyaa.si/view/797803

Thanks in advance.

**Comment by thegreatestminer** [comment]
:+1:

**Comment by thegreatestminer** [comment]
https://weeb.ztgasdf.workers.dev/0:/Shigofumi/

done!

**Comment by DankMemzYT** [comment]
Thanks again.
