### ISSUE TITLE
[BDMV] Yahari Ore no Seishun Love Comedy wa Machigatteiru S1+S2

### ISSUE THREAD

**Issue by sifadil3** [thegreatestminer/acp#27]
Hello.
Any chance you can get these two torrents:
https://nyaa.si/view/1174247
https://nyaa.si/view/1174580
Thanks a lot.

**Comment by thegreatestminer** [comment]
I'll try, but low seeders.

**Comment by thegreatestminer** [comment]
Alright, so the nyaa.si torrents are dead, but I'm getting the BDMVs from somewhere else instead. It should be done by tonight.

**Comment by sifadil3** [comment]
Ah ok. Thanks a lot.

**Comment by thegreatestminer** [comment]
Finally done.

https://weeb.ztgasdf.workers.dev/0:/Yahari%20Ore%20no%20Seishun%20Love%20Comedy%20wa%20Machigatteiru/JP%20BDMV/
