### ISSUE TITLE
3 Requests

### ISSUE THREAD

**Issue by DankMemzYT** [thegreatestminer/acp#28]
Kimi ni Todoke
https://nyaa.si/view/346999
https://nyaa.si/view/359344

Hourou Musuko
https://nyaa.si/view/517640

Shirobako
https://nyaa.si/view/926446

Thanks again in advance.

**Comment by thegreatestminer** [comment]
Sorry for the week long delay, I'll start working on this.

**Comment by thegreatestminer** [comment]
Your specified torrents have been uploaded to the directory.

I'm also adding some extra releases for Shirobako and Hourou Musuko, so expect to see more in those directories soon.

https://weeb.ztgasdf.workers.dev/0:/Kimi%20ni%20Todoke/
https://weeb.ztgasdf.workers.dev/0:/Hourou%20Musuko/
https://weeb.ztgasdf.workers.dev/0:/Shirobako/

**Comment by DankMemzYT** [comment]
No problem, and thanks!
