### ISSUE TITLE
Black Clover 01-90 (BD) + 91- (WEB)

### ISSUE THREAD

**Issue by seedtheworld** [thegreatestminer/acp#4]
Hello @thegreatestminer hope you're doing well. 
It seems your troubles with my requests won't end 😓
Anyways, I was wondering if you could add Black Clover to your archive. Of course there's no rush because I plan to watch it sometime in the future...

Here's BD for 01-90:
https://nyaa.si/view/1219913

The rest you can choose the source. HS or Erai.
PS. Erai provides ddl in their site so I don't think it's necessary to add Erai's.

Sorry for any inconvenience.

**Comment by thegreatestminer** [comment]
I will try to get this torrent, and please, keep going with the requests! They give me motivation to keep going. :D

I will probably download Judas's release for 1-123 and the rest from HorribleSubs.

**Comment by seedtheworld** [comment]
@thegreatestminer thank you!

**Comment by thegreatestminer** [comment]
Alright, Moozzi2's download is going absurdly slow. I'll probably continue to download this over the week, and hopefully I will get it up sooner or later.

I will work on adding Judas's and HorribleSubs's release for the time being.

**Comment by seedtheworld** [comment]
Thank you.

**Comment by thegreatestminer** [comment]
Alright, releases from Judas and HorribleSubs are now available.

https://weeb.ztgasdf.workers.dev/Black%20Clover/

I'll try to get Moozzi2's release as well, but if it downloads too slowly for a prolonged time, I will not get it.

**Comment by seedtheworld** [comment]
Thank you very much.

**Comment by thegreatestminer** [comment]
Moozzi2 torrent has been dropped, as it has been *five* days and I was able to get ~20GB.
