### ISSUE TITLE
3 Anime request

### ISSUE THREAD

**Issue by thatanimeguy** [thegreatestminer/acp#6]
Hi can you grab these 3 anime?

Attack on Titans s01-03
https://nyaa.si/view/1251934

Hyouka
https://nyaa.si/view/1251929

Senryuu Shoujo
https://nyaa.si/view/1251700 REMUX 
If there are any other 1080p BD versions for this show. 

Thanks man!

**Comment by thegreatestminer** [comment]
I will work on it.

**Comment by thegreatestminer** [comment]
US BDMV and DmonHiro's release of Senryuu Shoujo is now available.

**Comment by thegreatestminer** [comment]
MK-SCY and SCY's release of Attack on Titan is now available.

https://weeb.ztgasdf.workers.dev/Shingeki%20no%20Kyojin/

**Comment by seedtheworld** [comment]
Thank you bro. You're a lifesaver.

**Comment by thegreatestminer** [comment]
Beatrice-Raws's release of Hyouka is now available.
VCB-Studio's release is also available, and Coalgirls's release will come soon.

https://weeb.ztgasdf.workers.dev/Hyouka/
