### ISSUE TITLE
Haikyu!! BD 1080p Collection

### ISSUE THREAD

**Issue by seedtheworld** [thegreatestminer/acp#9]
Hi. I saw you exempt Haikyu from your ban list so I thought you should upload it.
Here are the links:

S01
https://nyaa.si/view/982442
Bakabt alternative high speed and freeleech:
https://bakabt.me/torrent/346610/haikyuu-bd-1080p-ac

S02
https://nyaa.si/view/1058619

S03
https://nyaa.si/view/1215189

S04
https://nyaa.si/view/1235183

OVAs
https://nyaa.si/view/918387
https://nyaa.si/view/919669
https://nyaa.si/view/1217885

Movies (compilations, so not necessary)
https://nyaa.si/view/1248441

Thanks.

**Comment by thegreatestminer** [comment]
I actually already have AC's release for S1+S2, but I don't have anything else. I'll work on this soon!!

**Comment by seedtheworld** [comment]
Wow. Ty

**Comment by thegreatestminer** [comment]
Alright. I downloaded everything except for the recap movies. I'm am indeed getting the recap movies, but they will come later. Folder should be up in a few moments.

**Comment by thegreatestminer** [comment]
It finished uploading. (205GB)
https://weeb.ztgasdf.workers.dev/Haikyuu/

Recap movies coming soon. I'll keep this issue open until I finish uploading them.

**Comment by thegreatestminer** [comment]
Recap movies have been uploaded, and this concludes this request. Thank you for requesting!

**Comment by seedtheworld** [comment]
> Recap movies have been uploaded, and this concludes this request. Thank you for requesting!

No! Not at all! 

Thank YOU for uploading.
